name: "\U0001FAB2 Bug report"
description: "Report bugs and unexpected behavior."
title: "[BUG]"
labels: ["bug", "ml-internal"]
assignees: []

body:
  - type: markdown
    attributes:
      value: "Thank you for reporting a bug! Before you get started, please [search to see](https://github.com/argilla-io/distilabel/issues) if an issue already exists for the bug you encountered."

  - type: textarea
    id: bug_description
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of the bug."
    validations:
      required: true

  - type: textarea
    id: stacktrace
    attributes:
      label: "To reproduce"
      description: "The code to reproduce the behavior."
      placeholder: |
        ```python
        my_python_code
        ```
    validations:
      required: false

  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem."
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: "Since version 1.16.0 you can use `python -m argilla info` command to easily get the used versions."
      value: |
        - Distilabel Version [e.g. 1.0.0]:
        - Python Version [e.g. 3.11]:
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional context"
      description: "Add any other relevant information."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        📌  Make sure you have provided all the required information in each section so we can support you properly.
